---
image: registry.pludoni.com/administrators/docker-images/rails-base:v17
stages: [checks, test, deploy]

variables:
  deploy_host: 'product03'
  deploy_name: 'hrfilter'

include:
  - project: 'administrators/gitlab-ci-yml'
    file: '/rails_default.yml'
